.TH "/home/scott/school/capstone/Task-Organizer/src/examples/cliparser.py" 3 "Sat Sep 24 2011" "Task-Organizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/scott/school/capstone/Task-Organizer/src/examples/cliparser.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcliparser::CLIParser\fP"
.br
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "namespace \fBcliparser\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Task-Organizer from the source code'\&.
