.TH "/home/scott/school/capstone/Task-Organizer/src/task/controller.py" 3 "Sat Sep 24 2011" "Task-Organizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/scott/school/capstone/Task-Organizer/src/task/controller.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcontroller::Controller\fP"
.br
.RI "\fIInterface to manipulate Tasks'\&. \fP"
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "namespace \fBcontroller\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Task-Organizer from the source code'\&.
