.TH "controller" 3 "Wed Sep 28 2011" "Task-Organizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
controller \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBController\fP"
.br
.RI "\fIInterface to manipulate Tasks'\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Task-Organizer from the source code'\&.
