.TH "ctask::CLIParser" 3 "Wed Sep 28 2011" "Task-Organizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ctask::CLIParser \- 
.PP
Parser for a cli program using the task package'\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBparse_cl_args\fP"
.br
.RI "\fIReturn a dictionary of arguments'\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Parser for a cli program using the task package'\&. 

Public Classes: \fBCLIParser\fP
.PP
Configures a command line parser and provides a means to invoke it on command line arguments'\&. 
.PP
Definition at line 70 of file ctask\&.py'\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def ctask::CLIParser::__init__ (self, storage_type, task_dbname = \fC'taskdb'\fP, task_filename = \fC'taskfile'\fP, key_filename = \fC'keyfile'\fP)"
.PP
Definition at line 71 of file ctask\&.py'\&.
.SH "Member Function Documentation"
.PP 
.SS "def ctask::CLIParser::parse_cl_args (self)"
.PP
Return a dictionary of arguments'\&. Calls the argument parser to parse the command line arguments by using sys'\&.argv'\&. Then calls a sanitizer to get an argument dictionary which is returned'\&. 
.PP
Definition at line 221 of file ctask\&.py'\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Task-Organizer from the source code'\&.
