.TH "/home/scott/school/capstone/Task-Organizer/src/examples/ctask.py" 3 "Sat Sep 24 2011" "Task-Organizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/scott/school/capstone/Task-Organizer/src/examples/ctask.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Packages"

.in +1c
.ti -1c
.RI "namespace \fBctask\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBctask::main\fP"
.br
.RI "\fICommand line implementation of task library'\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Task-Organizer from the source code'\&.
