.TH "/home/scott/school/capstone/Task-Organizer/src/task/logger.py" 3 "Sat Sep 24 2011" "Task-Organizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/scott/school/capstone/Task-Organizer/src/task/logger.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Packages"

.in +1c
.ti -1c
.RI "namespace \fBlogger\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBlogger::LOG\fP = logging\&.getLogger()"
.br
.ti -1c
.RI "tuple \fBlogger::FORMATTER\fP"
.br
.ti -1c
.RI "tuple \fBlogger::HANDLER\fP = logging\&.StreamHandler(sys\&.stderr)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Task-Organizer from the source code'\&.
