.TH "logger" 3 "Wed Sep 28 2011" "Task-Organizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
logger \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBLOG\fP = logging\&.getLogger()"
.br
.ti -1c
.RI "tuple \fBFORMATTER\fP"
.br
.ti -1c
.RI "tuple \fBHANDLER\fP = logging\&.StreamHandler(sys\&.stderr)"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "tuple \fBlogger::FORMATTER\fP"\fBInitial value:\fP
.PP
.nf
1 logging\&.Formatter(
2     fmt='[%(asctime)s] %(levelname)s:%(name)s:'
3     '%(module)s\&.%(funcName)s(): %(message)s')
.fi
.PP
Definition at line 15 of file logger\&.py'\&.
.SS "tuple \fBlogger::HANDLER\fP = logging\&.StreamHandler(sys\&.stderr)"
.PP
Definition at line 19 of file logger\&.py'\&.
.SS "tuple \fBlogger::LOG\fP = logging\&.getLogger()"
.PP
Definition at line 12 of file logger\&.py'\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Task-Organizer from the source code'\&.
