.TH "/home/scott/school/capstone/Task-Organizer/src/task/storage.py" 3 "Sat Sep 24 2011" "Task-Organizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/scott/school/capstone/Task-Organizer/src/task/storage.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBstorage::Storage\fP"
.br
.RI "\fIAbstract base class for Task storage'\&. \fP"
.ti -1c
.RI "class \fBstorage::FileStorage\fP"
.br
.RI "\fIInterface for storing Tasks to a file'\&. \fP"
.ti -1c
.RI "class \fBstorage::SQLiteStorage\fP"
.br
.RI "\fIInterface for storing Tasks to a SQLite database'\&. \fP"
.ti -1c
.RI "class \fBstorage::GTaskStorage\fP"
.br
.RI "\fIInterface for storing Tasks to Google Tasks'\&. \fP"
.ti -1c
.RI "class \fBstorage::StorageFactory\fP"
.br
.RI "\fIInterface for getting a storage instance'\&. \fP"
.ti -1c
.RI "class \fBstorage::_KeyGenerator\fP"
.br
.RI "\fIGenerate unique keys for Tasks'\&. \fP"
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "namespace \fBstorage\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBstorage::FLAGS\fP = gflags\&.FLAGS"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Task-Organizer from the source code'\&.
