.TH "storage" 3 "Sat Sep 24 2011" "Task-Organizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
storage \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBStorage\fP"
.br
.RI "\fIAbstract base class for Task storage'\&. \fP"
.ti -1c
.RI "class \fBFileStorage\fP"
.br
.RI "\fIInterface for storing Tasks to a file'\&. \fP"
.ti -1c
.RI "class \fBSQLiteStorage\fP"
.br
.RI "\fIInterface for storing Tasks to a SQLite database'\&. \fP"
.ti -1c
.RI "class \fBGTaskStorage\fP"
.br
.RI "\fIInterface for storing Tasks to Google Tasks'\&. \fP"
.ti -1c
.RI "class \fBStorageFactory\fP"
.br
.RI "\fIInterface for getting a storage instance'\&. \fP"
.ti -1c
.RI "class \fB_KeyGenerator\fP"
.br
.RI "\fIGenerate unique keys for Tasks'\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBFLAGS\fP = gflags\&.FLAGS"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBstorage::FLAGS\fP = gflags\&.FLAGS"
.PP
Definition at line 599 of file storage\&.py'\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Task-Organizer from the source code'\&.
