.TH "storage::Storage" 3 "Sat Sep 24 2011" "Task-Organizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
storage::Storage \- 
.PP
Abstract base class for Task storage'\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBstorage::FileStorage\fP, \fBstorage::GTaskStorage\fP, and \fBstorage::SQLiteStorage\fP'\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBadd\fP"
.br
.RI "\fIThis functions is to be overridden by a specific storage method'\&. \fP"
.ti -1c
.RI "def \fBfind\fP"
.br
.RI "\fIThis functions is to be overridden by a specific storage method'\&. \fP"
.ti -1c
.RI "def \fBget_all\fP"
.br
.RI "\fIThis functions is to be overridden by a specific storage method'\&. \fP"
.ti -1c
.RI "def \fBupdate\fP"
.br
.RI "\fIThis functions is to be overridden by a specific storage method'\&. \fP"
.ti -1c
.RI "def \fBdelete\fP"
.br
.RI "\fIThis functions is to be overridden by a specific storage method'\&. \fP"
.ti -1c
.RI "def \fBsearch\fP"
.br
.RI "\fIThis functions is to be overridden by a specific storage method'\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Abstract base class for Task storage'\&. 

Public methods: add(task_item) find(key = None) \fBget_all()\fP update(task_item) delete(key) search(search_task) 
.PP
Definition at line 41 of file storage\&.py'\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def storage::Storage::__init__ (self)"
.PP
Reimplemented in \fBstorage::GTaskStorage\fP'\&.
.PP
Definition at line 42 of file storage\&.py'\&.
.SH "Member Function Documentation"
.PP 
.SS "def storage::Storage::add (self, task_item)"
.PP
This functions is to be overridden by a specific storage method'\&. 
.PP
Reimplemented in \fBstorage::GTaskStorage\fP, \fBstorage::SQLiteStorage\fP, and \fBstorage::FileStorage\fP'\&.
.PP
Definition at line 47 of file storage\&.py'\&.
.SS "def storage::Storage::delete (self, key)"
.PP
This functions is to be overridden by a specific storage method'\&. 
.PP
Reimplemented in \fBstorage::GTaskStorage\fP, \fBstorage::SQLiteStorage\fP, and \fBstorage::FileStorage\fP'\&.
.PP
Definition at line 67 of file storage\&.py'\&.
.SS "def storage::Storage::find (self, key = \fCNone\fP)"
.PP
This functions is to be overridden by a specific storage method'\&. 
.PP
Reimplemented in \fBstorage::GTaskStorage\fP, \fBstorage::SQLiteStorage\fP, and \fBstorage::FileStorage\fP'\&.
.PP
Definition at line 52 of file storage\&.py'\&.
.SS "def storage::Storage::get_all (self)"
.PP
This functions is to be overridden by a specific storage method'\&. 
.PP
Reimplemented in \fBstorage::GTaskStorage\fP, \fBstorage::SQLiteStorage\fP, and \fBstorage::FileStorage\fP'\&.
.PP
Definition at line 57 of file storage\&.py'\&.
.SS "def storage::Storage::search (self, search_task)"
.PP
This functions is to be overridden by a specific storage method'\&. 
.PP
Reimplemented in \fBstorage::GTaskStorage\fP, \fBstorage::SQLiteStorage\fP, and \fBstorage::FileStorage\fP'\&.
.PP
Definition at line 72 of file storage\&.py'\&.
.SS "def storage::Storage::update (self, task_item)"
.PP
This functions is to be overridden by a specific storage method'\&. 
.PP
Reimplemented in \fBstorage::GTaskStorage\fP, \fBstorage::SQLiteStorage\fP, and \fBstorage::FileStorage\fP'\&.
.PP
Definition at line 62 of file storage\&.py'\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Task-Organizer from the source code'\&.
