.TH "task::TaskCreator" 3 "Sat Sep 24 2011" "Task-Organizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
task::TaskCreator \- 
.PP
Create a \fBTask\fP instance automatically'\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBbuild\fP"
.br
.RI "\fICreates a \fBTask\fP instance given a dictionary'\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Create a \fBTask\fP instance automatically'\&. 

Public methods: build(arg_dict)
.PP
Create a \fBTask\fP instance in a automatic and safer manner'\&. 
.PP
Definition at line 79 of file task\&.py'\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def task::TaskCreator::__init__ (self)"
.PP
Definition at line 80 of file task\&.py'\&.
.SH "Member Function Documentation"
.PP 
.SS "def task::TaskCreator::build (arg_dict)"
.PP
Creates a \fBTask\fP instance given a dictionary'\&. Args: arg_dict (dict): dictionary formatted to create a \fBTask\fP
.PP
The given dictionary must have a correct naming scheme'\&. However, it can be missing any field'\&. 
.PP
Definition at line 93 of file task\&.py'\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Task-Organizer from the source code'\&.
