.TH "/home/scott/school/capstone/Task-Organizer/src/task/task.py" 3 "Sat Sep 24 2011" "Task-Organizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/scott/school/capstone/Task-Organizer/src/task/task.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBtask::Task\fP"
.br
.RI "\fIInstantiate a \fBTask\fP object'\&. \fP"
.ti -1c
.RI "class \fBtask::TaskCreator\fP"
.br
.RI "\fICreate a \fBTask\fP instance automatically'\&. \fP"
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "namespace \fBtask\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Task-Organizer from the source code'\&.
