.TH "task::Task" 3 "Wed Sep 28 2011" "Task-Organizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
task::Task \- 
.PP
Instantiate a \fBTask\fP object'\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fB__str__\fP"
.br
.ti -1c
.RI "def \fB__eq__\fP"
.br
.ti -1c
.RI "def \fB__ne__\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBkey\fP"
.br
.ti -1c
.RI "\fBtitle\fP"
.br
.ti -1c
.RI "\fBnotes\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Instantiate a \fBTask\fP object'\&. 

Provides attributes for tasks and methods to compare \fBTask\fP instances'\&. 
.PP
Definition at line 21 of file task\&.py'\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def task::Task::__init__ (self, kwargs)"
.PP
Definition at line 22 of file task\&.py'\&.
.SH "Member Function Documentation"
.PP 
.SS "def task::Task::__eq__ (self, other)"
.PP
Definition at line 52 of file task\&.py'\&.
.SS "def task::Task::__ne__ (self, other)"
.PP
Definition at line 61 of file task\&.py'\&.
.SS "def task::Task::__str__ (self)"
.PP
Definition at line 42 of file task\&.py'\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBtask::Task::key\fP"
.PP
Definition at line 22 of file task\&.py'\&.
.SS "\fBtask::Task::notes\fP"
.PP
Definition at line 22 of file task\&.py'\&.
.SS "\fBtask::Task::title\fP"
.PP
Definition at line 22 of file task\&.py'\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Task-Organizer from the source code'\&.
