.TH "test_taskstorage::TestFileStorage" 3 "Sat Sep 24 2011" "Task-Organizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_taskstorage::TestFileStorage \- 
.PP
Tests specific to the FileStorage class'\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBtest_taskstorage::TestStorage\fP'\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBsetUp\fP"
.br
.ti -1c
.RI "def \fBtearDown\fP"
.br
.ti -1c
.RI "def \fBtest_add_read_fail\fP"
.br
.RI "\fITests add()'s handling of failed file reading'\&. \fP"
.ti -1c
.RI "def \fBtest_add_write_fail\fP"
.br
.RI "\fITests add()'s handling of failed file writing'\&. \fP"
.ti -1c
.RI "def \fBtest_find_read_fail\fP"
.br
.RI "\fITests find()'s handling of failed file reading'\&. \fP"
.ti -1c
.RI "def \fBtest_get_all_read_fail\fP"
.br
.RI "\fITests get_all()'s handling of failed file reading'\&. \fP"
.ti -1c
.RI "def \fBtest_update_write_fail\fP"
.br
.RI "\fITests update()'s handling of failed file writing'\&. \fP"
.ti -1c
.RI "def \fBtest_delete_write_fail\fP"
.br
.RI "\fITests delete()'s handling of failed file writing'\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBmy_task\fP"
.br
.ti -1c
.RI "\fBtest_task_filename\fP"
.br
.ti -1c
.RI "\fBtest_key_filename\fP"
.br
.ti -1c
.RI "\fBtask_storage\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Tests specific to the FileStorage class'\&. 

Tests that only apply to the implementation of the FileStorage class and not other task_storage types'\&. 
.PP
Definition at line 169 of file test_taskstorage\&.py'\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def test_taskstorage::TestFileStorage::__init__ (self, method_name)"
.PP
Reimplemented from \fBtest_taskstorage::TestStorage\fP'\&.
.PP
Definition at line 171 of file test_taskstorage\&.py'\&.
.SH "Member Function Documentation"
.PP 
.SS "def test_taskstorage::TestFileStorage::setUp (self)"
.PP
Definition at line 174 of file test_taskstorage\&.py'\&.
.SS "def test_taskstorage::TestFileStorage::tearDown (self)"
.PP
Definition at line 190 of file test_taskstorage\&.py'\&.
.SS "def test_taskstorage::TestFileStorage::test_add_read_fail (self)"
.PP
Tests add()'s handling of failed file reading'\&. 
.PP
Definition at line 200 of file test_taskstorage\&.py'\&.
.SS "def test_taskstorage::TestFileStorage::test_add_write_fail (self)"
.PP
Tests add()'s handling of failed file writing'\&. 
.PP
Definition at line 210 of file test_taskstorage\&.py'\&.
.SS "def test_taskstorage::TestFileStorage::test_delete_write_fail (self)"
.PP
Tests delete()'s handling of failed file writing'\&. 
.PP
Definition at line 245 of file test_taskstorage\&.py'\&.
.SS "def test_taskstorage::TestFileStorage::test_find_read_fail (self)"
.PP
Tests find()'s handling of failed file reading'\&. 
.PP
Definition at line 217 of file test_taskstorage\&.py'\&.
.SS "def test_taskstorage::TestFileStorage::test_get_all_read_fail (self)"
.PP
Tests get_all()'s handling of failed file reading'\&. 
.PP
Definition at line 227 of file test_taskstorage\&.py'\&.
.SS "def test_taskstorage::TestFileStorage::test_update_write_fail (self)"
.PP
Tests update()'s handling of failed file writing'\&. 
.PP
Definition at line 237 of file test_taskstorage\&.py'\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBtest_taskstorage::TestFileStorage::my_task\fP"
.PP
Reimplemented from \fBtest_taskstorage::TestStorage\fP'\&.
.PP
Definition at line 174 of file test_taskstorage\&.py'\&.
.SS "\fBtest_taskstorage::TestFileStorage::task_storage\fP"
.PP
Reimplemented from \fBtest_taskstorage::TestStorage\fP'\&.
.PP
Definition at line 174 of file test_taskstorage\&.py'\&.
.SS "\fBtest_taskstorage::TestFileStorage::test_key_filename\fP"
.PP
Definition at line 174 of file test_taskstorage\&.py'\&.
.SS "\fBtest_taskstorage::TestFileStorage::test_task_filename\fP"
.PP
Definition at line 174 of file test_taskstorage\&.py'\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Task-Organizer from the source code'\&.
