.TH "/home/scott/school/capstone/Task-Organizer/src/test/test_task.py" 3 "Sat Sep 24 2011" "Task-Organizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/scott/school/capstone/Task-Organizer/src/test/test_task.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBtest_task::TestTask\fP"
.br
.RI "\fITests Task objects'\&. \fP"
.ti -1c
.RI "class \fBtest_task::TestTaskCreator\fP"
.br
.RI "\fITests that TaskCreator correctly creates Task objects'\&. \fP"
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "namespace \fBtest_task\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBtest_task::VERBOSITY\fP = util\&.verbosity_helper()"
.br
.ti -1c
.RI "tuple \fBtest_task::SUITE\fP = unittest\&.TestLoader()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Task-Organizer from the source code'\&.
