.TH "test_ctask" 3 "Wed Sep 28 2011" "Task-Organizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_ctask \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTestCTask\fP"
.br
.RI "\fITests parsing of the command line for the ctask script'\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBVERBOSITY\fP = util\&.verbosity_helper()"
.br
.ti -1c
.RI "tuple \fBSUITE\fP = unittest\&.TestLoader()"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "tuple \fBtest_ctask::SUITE\fP = unittest\&.TestLoader()"
.PP
Definition at line 113 of file test_ctask\&.py'\&.
.SS "tuple \fBtest_ctask::VERBOSITY\fP = util\&.verbosity_helper()"
.PP
Definition at line 111 of file test_ctask\&.py'\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Task-Organizer from the source code'\&.
