.TH "test_task::TestTask" 3 "Wed Sep 28 2011" "Task-Organizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_task::TestTask \- 
.PP
Tests Task objects'\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBsetUp\fP"
.br
.ti -1c
.RI "def \fBtearDown\fP"
.br
.ti -1c
.RI "def \fBtest_equal\fP"
.br
.RI "\fITests a Task's handling when compared to an equivalent Task'\&. \fP"
.ti -1c
.RI "def \fBtest_equal_false\fP"
.br
.RI "\fITests a Task's handling when == returns False'\&. \fP"
.ti -1c
.RI "def \fBtest_not_equal\fP"
.br
.RI "\fITests a Task's handling when != returns True'\&. \fP"
.ti -1c
.RI "def \fBtest_equal_false_instance\fP"
.br
.RI "\fITests a Task's handling when == compares to a Task instance'\&. \fP"
.ti -1c
.RI "def \fBtest_not_equal_instance\fP"
.br
.RI "\fITests a Task's handling when != compares to a non-Task instance'\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBmy_task\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Tests Task objects'\&. 
.PP
Definition at line 8 of file test_task\&.py'\&.
.SH "Member Function Documentation"
.PP 
.SS "def test_task::TestTask::setUp (self)"
.PP
Definition at line 10 of file test_task\&.py'\&.
.SS "def test_task::TestTask::tearDown (self)"
.PP
Definition at line 16 of file test_task\&.py'\&.
.SS "def test_task::TestTask::test_equal (self)"
.PP
Tests a Task's handling when compared to an equivalent Task'\&. 
.PP
Definition at line 22 of file test_task\&.py'\&.
.SS "def test_task::TestTask::test_equal_false (self)"
.PP
Tests a Task's handling when == returns False'\&. 
.PP
Definition at line 29 of file test_task\&.py'\&.
.SS "def test_task::TestTask::test_equal_false_instance (self)"
.PP
Tests a Task's handling when == compares to a Task instance'\&. 
.PP
Definition at line 50 of file test_task\&.py'\&.
.SS "def test_task::TestTask::test_not_equal (self)"
.PP
Tests a Task's handling when != returns True'\&. 
.PP
Definition at line 38 of file test_task\&.py'\&.
.SS "def test_task::TestTask::test_not_equal_instance (self)"
.PP
Tests a Task's handling when != compares to a non-Task instance'\&. 
.PP
Definition at line 59 of file test_task\&.py'\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBtest_task::TestTask::my_task\fP"
.PP
Definition at line 10 of file test_task\&.py'\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Task-Organizer from the source code'\&.
