.TH "/home/scott/school/capstone/Task-Organizer/src/test/test_taskcontroller.py" 3 "Sat Sep 24 2011" "Task-Organizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/scott/school/capstone/Task-Organizer/src/test/test_taskcontroller.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBtest_taskcontroller::TestTaskController\fP"
.br
.RI "\fIAbstract tests for child tests using specific storage types'\&. \fP"
.ti -1c
.RI "class \fBtest_taskcontroller::TestTaskControllerFileStorage\fP"
.br
.RI "\fITests the TaskController while using file storage'\&. \fP"
.ti -1c
.RI "class \fBtest_taskcontroller::TestTaskControllerSQLiteStorage\fP"
.br
.RI "\fITests the TaskController while using sqlite storage'\&. \fP"
.ti -1c
.RI "class \fBtest_taskcontroller::TestTaskControllerGTaskStorage\fP"
.br
.RI "\fITests the TaskController while using GTask storage'\&. \fP"
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "namespace \fBtest_taskcontroller\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBtest_taskcontroller::VERBOSITY\fP = util\&.verbosity_helper()"
.br
.ti -1c
.RI "tuple \fBtest_taskcontroller::SUITE\fP = unittest\&.TestLoader()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Task-Organizer from the source code'\&.
