.TH "test_taskstorage" 3 "Wed Sep 28 2011" "Task-Organizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_taskstorage \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTestStorage\fP"
.br
.RI "\fIAbstract tests for the child classes of the Storage class'\&. \fP"
.ti -1c
.RI "class \fBTestGenericStorage\fP"
.br
.RI "\fITests the Storage abstract base class directly'\&. \fP"
.ti -1c
.RI "class \fBTestFileStorage\fP"
.br
.RI "\fITests specific to the FileStorage class'\&. \fP"
.ti -1c
.RI "class \fBTestSQLiteStorage\fP"
.br
.RI "\fITests specific to the SQLiteStorage class'\&. \fP"
.ti -1c
.RI "class \fBTestGTaskStorage\fP"
.br
.RI "\fITests specific to the GTaskStorage class'\&. \fP"
.ti -1c
.RI "class \fBTestKeyGenerator\fP"
.br
.RI "\fITests for the KeyGenerator class'\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBVERBOSITY\fP = util\&.verbosity_helper()"
.br
.ti -1c
.RI "tuple \fBSUITE\fP = unittest\&.TestLoader()"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "tuple \fBtest_taskstorage::SUITE\fP = unittest\&.TestLoader()"
.PP
Definition at line 392 of file test_taskstorage\&.py'\&.
.SS "tuple \fBtest_taskstorage::VERBOSITY\fP = util\&.verbosity_helper()"
.PP
Definition at line 390 of file test_taskstorage\&.py'\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Task-Organizer from the source code'\&.
