.TH "test_taskstorage::TestStorage" 3 "Wed Sep 28 2011" "Task-Organizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_taskstorage::TestStorage \- 
.PP
Abstract tests for the child classes of the Storage class'\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBtest_taskstorage::TestFileStorage\fP, \fBtest_taskstorage::TestGTaskStorage\fP, and \fBtest_taskstorage::TestSQLiteStorage\fP'\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBtest_add\fP"
.br
.RI "\fITests that add() correctly adds a Task to storage'\&. \fP"
.ti -1c
.RI "def \fBtest_find\fP"
.br
.RI "\fITests that find() correctly returns a Task given a key'\&. \fP"
.ti -1c
.RI "def \fBtest_get_all\fP"
.br
.RI "\fITests that get_all() returns a list of all Tasks'\&. \fP"
.ti -1c
.RI "def \fBtest_update\fP"
.br
.RI "\fITests that update() correctly updates a Task given a Task'\&. \fP"
.ti -1c
.RI "def \fBtest_update_no_match\fP"
.br
.RI "\fITests updates()'s handling of no matching key'\&. \fP"
.ti -1c
.RI "def \fBtest_delete\fP"
.br
.RI "\fITests that delete() correctly deletes a Task from storage'\&. \fP"
.ti -1c
.RI "def \fBtest_delete_no_match\fP"
.br
.RI "\fITests delete()'s handling of no matching key'\&. \fP"
.ti -1c
.RI "def \fBtest_search\fP"
.br
.RI "\fITests that search() correctly returns a matching Task given a Task'\&. \fP"
.ti -1c
.RI "def \fBtest_search_not_found\fP"
.br
.RI "\fITests search()'s behavior when no match is found'\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBtask_storage\fP"
.br
.ti -1c
.RI "\fBmy_task\fP"
.br
.ti -1c
.RI "\fBkey\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Abstract tests for the child classes of the Storage class'\&. 

This abstract test case's functions should be called only through a child test case'\&. 
.PP
Definition at line 20 of file test_taskstorage\&.py'\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def test_taskstorage::TestStorage::__init__ (self, method_name)"
.PP
Reimplemented in \fBtest_taskstorage::TestGTaskStorage\fP, \fBtest_taskstorage::TestSQLiteStorage\fP, and \fBtest_taskstorage::TestFileStorage\fP'\&.
.PP
Definition at line 22 of file test_taskstorage\&.py'\&.
.SH "Member Function Documentation"
.PP 
.SS "def test_taskstorage::TestStorage::test_add (self)"
.PP
Tests that add() correctly adds a Task to storage'\&. 
.PP
Definition at line 29 of file test_taskstorage\&.py'\&.
.SS "def test_taskstorage::TestStorage::test_delete (self)"
.PP
Tests that delete() correctly deletes a Task from storage'\&. 
.PP
Definition at line 79 of file test_taskstorage\&.py'\&.
.SS "def test_taskstorage::TestStorage::test_delete_no_match (self)"
.PP
Tests delete()'s handling of no matching key'\&. 
.PP
Definition at line 90 of file test_taskstorage\&.py'\&.
.SS "def test_taskstorage::TestStorage::test_find (self)"
.PP
Tests that find() correctly returns a Task given a key'\&. 
.PP
Definition at line 39 of file test_taskstorage\&.py'\&.
.SS "def test_taskstorage::TestStorage::test_get_all (self)"
.PP
Tests that get_all() returns a list of all Tasks'\&. 
.PP
Definition at line 47 of file test_taskstorage\&.py'\&.
.SS "def test_taskstorage::TestStorage::test_search (self)"
.PP
Tests that search() correctly returns a matching Task given a Task'\&. 
.PP
Definition at line 101 of file test_taskstorage\&.py'\&.
.SS "def test_taskstorage::TestStorage::test_search_not_found (self)"
.PP
Tests search()'s behavior when no match is found'\&. 
.PP
Definition at line 110 of file test_taskstorage\&.py'\&.
.SS "def test_taskstorage::TestStorage::test_update (self)"
.PP
Tests that update() correctly updates a Task given a Task'\&. 
.PP
Definition at line 55 of file test_taskstorage\&.py'\&.
.SS "def test_taskstorage::TestStorage::test_update_no_match (self)"
.PP
Tests updates()'s handling of no matching key'\&. 
.PP
Definition at line 66 of file test_taskstorage\&.py'\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBtest_taskstorage::TestStorage::key\fP"
.PP
Definition at line 66 of file test_taskstorage\&.py'\&.
.SS "\fBtest_taskstorage::TestStorage::my_task\fP"
.PP
Reimplemented in \fBtest_taskstorage::TestGTaskStorage\fP, \fBtest_taskstorage::TestSQLiteStorage\fP, and \fBtest_taskstorage::TestFileStorage\fP'\&.
.PP
Definition at line 22 of file test_taskstorage\&.py'\&.
.SS "\fBtest_taskstorage::TestStorage::task_storage\fP"
.PP
Reimplemented in \fBtest_taskstorage::TestGTaskStorage\fP, \fBtest_taskstorage::TestSQLiteStorage\fP, and \fBtest_taskstorage::TestFileStorage\fP'\&.
.PP
Definition at line 22 of file test_taskstorage\&.py'\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Task-Organizer from the source code'\&.
