.TH "/home/scott/school/capstone/Task-Organizer/src/test/test_taskstorage.py" 3 "Sat Sep 24 2011" "Task-Organizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/scott/school/capstone/Task-Organizer/src/test/test_taskstorage.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBtest_taskstorage::TestStorage\fP"
.br
.RI "\fIAbstract tests for the child classes of the Storage class'\&. \fP"
.ti -1c
.RI "class \fBtest_taskstorage::TestGenericStorage\fP"
.br
.RI "\fITests the Storage abstract base class directly'\&. \fP"
.ti -1c
.RI "class \fBtest_taskstorage::TestFileStorage\fP"
.br
.RI "\fITests specific to the FileStorage class'\&. \fP"
.ti -1c
.RI "class \fBtest_taskstorage::TestSQLiteStorage\fP"
.br
.RI "\fITests specific to the SQLiteStorage class'\&. \fP"
.ti -1c
.RI "class \fBtest_taskstorage::TestGTaskStorage\fP"
.br
.RI "\fITests specific to the GTaskStorage class'\&. \fP"
.ti -1c
.RI "class \fBtest_taskstorage::TestKeyGenerator\fP"
.br
.RI "\fITests for the KeyGenerator class'\&. \fP"
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "namespace \fBtest_taskstorage\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBtest_taskstorage::VERBOSITY\fP = util\&.verbosity_helper()"
.br
.ti -1c
.RI "tuple \fBtest_taskstorage::SUITE\fP = unittest\&.TestLoader()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Task-Organizer from the source code'\&.
