.TH "test_taskstorage::TestGenericStorage" 3 "Sat Sep 24 2011" "Task-Organizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_taskstorage::TestGenericStorage \- 
.PP
Tests the Storage abstract base class directly'\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBsetUp\fP"
.br
.ti -1c
.RI "def \fBtearDown\fP"
.br
.ti -1c
.RI "def \fBtest_not_implemented\fP"
.br
.RI "\fITests error handling in storage's abstract functions'\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBmy_task\fP"
.br
.ti -1c
.RI "\fBstorage_instance\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Tests the Storage abstract base class directly'\&. 

Tests that Storage abstract base class handles direct instantiations'\&. 
.PP
Definition at line 123 of file test_taskstorage\&.py'\&.
.SH "Member Function Documentation"
.PP 
.SS "def test_taskstorage::TestGenericStorage::setUp (self)"
.PP
Definition at line 125 of file test_taskstorage\&.py'\&.
.SS "def test_taskstorage::TestGenericStorage::tearDown (self)"
.PP
Definition at line 129 of file test_taskstorage\&.py'\&.
.SS "def test_taskstorage::TestGenericStorage::test_not_implemented (self)"
.PP
Tests error handling in storage's abstract functions'\&. 
.PP
Definition at line 134 of file test_taskstorage\&.py'\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBtest_taskstorage::TestGenericStorage::my_task\fP"
.PP
Definition at line 125 of file test_taskstorage\&.py'\&.
.SS "\fBtest_taskstorage::TestGenericStorage::storage_instance\fP"
.PP
Definition at line 125 of file test_taskstorage\&.py'\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Task-Organizer from the source code'\&.
