.TH "test_taskcontroller" 3 "Wed Sep 28 2011" "Task-Organizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_taskcontroller \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTestTaskController\fP"
.br
.RI "\fIAbstract tests for child tests using specific storage types'\&. \fP"
.ti -1c
.RI "class \fBTestTaskControllerFileStorage\fP"
.br
.RI "\fITests the TaskController while using file storage'\&. \fP"
.ti -1c
.RI "class \fBTestTaskControllerSQLiteStorage\fP"
.br
.RI "\fITests the TaskController while using sqlite storage'\&. \fP"
.ti -1c
.RI "class \fBTestTaskControllerGTaskStorage\fP"
.br
.RI "\fITests the TaskController while using GTask storage'\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBVERBOSITY\fP = util\&.verbosity_helper()"
.br
.ti -1c
.RI "tuple \fBSUITE\fP = unittest\&.TestLoader()"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "tuple \fBtest_taskcontroller::SUITE\fP = unittest\&.TestLoader()"
.PP
Definition at line 219 of file test_taskcontroller\&.py'\&.
.SS "tuple \fBtest_taskcontroller::VERBOSITY\fP = util\&.verbosity_helper()"
.PP
Definition at line 217 of file test_taskcontroller\&.py'\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Task-Organizer from the source code'\&.
