.TH "test_taskcontroller::TestTaskControllerFileStorage" 3 "Sat Sep 24 2011" "Task-Organizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_taskcontroller::TestTaskControllerFileStorage \- 
.PP
Tests the TaskController while using file storage'\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBtest_taskcontroller::TestTaskController\fP'\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBsetUp\fP"
.br
.ti -1c
.RI "def \fBtearDown\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBtest_task_filename\fP"
.br
.ti -1c
.RI "\fBtest_key_filename\fP"
.br
.ti -1c
.RI "\fBinterface_controller\fP"
.br
.ti -1c
.RI "\fBtitle\fP"
.br
.ti -1c
.RI "\fBnotes\fP"
.br
.ti -1c
.RI "\fBkey\fP"
.br
.ti -1c
.RI "\fBadded_task\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Tests the TaskController while using file storage'\&. 
.PP
Definition at line 133 of file test_taskcontroller\&.py'\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def test_taskcontroller::TestTaskControllerFileStorage::__init__ (self, method_name)"
.PP
Reimplemented from \fBtest_taskcontroller::TestTaskController\fP'\&.
.PP
Definition at line 135 of file test_taskcontroller\&.py'\&.
.SH "Member Function Documentation"
.PP 
.SS "def test_taskcontroller::TestTaskControllerFileStorage::setUp (self)"
.PP
Definition at line 138 of file test_taskcontroller\&.py'\&.
.SS "def test_taskcontroller::TestTaskControllerFileStorage::tearDown (self)"
.PP
Definition at line 160 of file test_taskcontroller\&.py'\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBtest_taskcontroller::TestTaskControllerFileStorage::added_task\fP"
.PP
Reimplemented from \fBtest_taskcontroller::TestTaskController\fP'\&.
.PP
Definition at line 138 of file test_taskcontroller\&.py'\&.
.SS "\fBtest_taskcontroller::TestTaskControllerFileStorage::interface_controller\fP"
.PP
Reimplemented from \fBtest_taskcontroller::TestTaskController\fP'\&.
.PP
Definition at line 138 of file test_taskcontroller\&.py'\&.
.SS "\fBtest_taskcontroller::TestTaskControllerFileStorage::key\fP"
.PP
Definition at line 138 of file test_taskcontroller\&.py'\&.
.SS "\fBtest_taskcontroller::TestTaskControllerFileStorage::notes\fP"
.PP
Reimplemented from \fBtest_taskcontroller::TestTaskController\fP'\&.
.PP
Definition at line 138 of file test_taskcontroller\&.py'\&.
.SS "\fBtest_taskcontroller::TestTaskControllerFileStorage::test_key_filename\fP"
.PP
Definition at line 138 of file test_taskcontroller\&.py'\&.
.SS "\fBtest_taskcontroller::TestTaskControllerFileStorage::test_task_filename\fP"
.PP
Definition at line 138 of file test_taskcontroller\&.py'\&.
.SS "\fBtest_taskcontroller::TestTaskControllerFileStorage::title\fP"
.PP
Reimplemented from \fBtest_taskcontroller::TestTaskController\fP'\&.
.PP
Definition at line 138 of file test_taskcontroller\&.py'\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Task-Organizer from the source code'\&.
