.TH "test_cliparser::TestCLIParser" 3 "Sat Sep 24 2011" "Task-Organizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_cliparser::TestCLIParser \- 
.PP
Tests parsing of the command line for the ctask script'\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBsetUp\fP"
.br
.ti -1c
.RI "def \fBtearDown\fP"
.br
.ti -1c
.RI "def \fBtest_add_subparser\fP"
.br
.RI "\fITests the parser when the add sub-command is specified'\&. \fP"
.ti -1c
.RI "def \fBtest_find_subparser\fP"
.br
.RI "\fITests the parser when the find sub-command is specified'\&. \fP"
.ti -1c
.RI "def \fBtest_edit_subparser\fP"
.br
.RI "\fITests the parser when the edit sub-command is specified'\&. \fP"
.ti -1c
.RI "def \fBtest_delete_subparser\fP"
.br
.RI "\fITests the parser when the del sub-command is specified'\&. \fP"
.ti -1c
.RI "def \fBtest_parse_cl_args\fP"
.br
.RI "\fITests that options are correctly transformed into a dict'\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBtest_task_filename\fP"
.br
.ti -1c
.RI "\fBtest_key_filename\fP"
.br
.ti -1c
.RI "\fBparser\fP"
.br
.ti -1c
.RI "\fBtitle\fP"
.br
.ti -1c
.RI "\fBnotes\fP"
.br
.ti -1c
.RI "\fBkey\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Tests parsing of the command line for the ctask script'\&. 


.PP
Definition at line 10 of file test_cliparser\&.py'\&.
.SH "Member Function Documentation"
.PP 
.SS "def test_cliparser::TestCLIParser::setUp (self)"
.PP
Definition at line 12 of file test_cliparser\&.py'\&.
.SS "def test_cliparser::TestCLIParser::tearDown (self)"
.PP
Definition at line 26 of file test_cliparser\&.py'\&.
.SS "def test_cliparser::TestCLIParser::test_add_subparser (self)"
.PP
Tests the parser when the add sub-command is specified'\&. 
.PP
Definition at line 32 of file test_cliparser\&.py'\&.
.SS "def test_cliparser::TestCLIParser::test_delete_subparser (self)"
.PP
Tests the parser when the del sub-command is specified'\&. 
.PP
Definition at line 78 of file test_cliparser\&.py'\&.
.SS "def test_cliparser::TestCLIParser::test_edit_subparser (self)"
.PP
Tests the parser when the edit sub-command is specified'\&. 
.PP
Definition at line 62 of file test_cliparser\&.py'\&.
.SS "def test_cliparser::TestCLIParser::test_find_subparser (self)"
.PP
Tests the parser when the find sub-command is specified'\&. 
.PP
Definition at line 48 of file test_cliparser\&.py'\&.
.SS "def test_cliparser::TestCLIParser::test_parse_cl_args (self)"
.PP
Tests that options are correctly transformed into a dict'\&. 
.PP
Definition at line 92 of file test_cliparser\&.py'\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBtest_cliparser::TestCLIParser::key\fP"
.PP
Definition at line 12 of file test_cliparser\&.py'\&.
.SS "\fBtest_cliparser::TestCLIParser::notes\fP"
.PP
Definition at line 12 of file test_cliparser\&.py'\&.
.SS "\fBtest_cliparser::TestCLIParser::parser\fP"
.PP
Definition at line 12 of file test_cliparser\&.py'\&.
.SS "\fBtest_cliparser::TestCLIParser::test_key_filename\fP"
.PP
Definition at line 12 of file test_cliparser\&.py'\&.
.SS "\fBtest_cliparser::TestCLIParser::test_task_filename\fP"
.PP
Definition at line 12 of file test_cliparser\&.py'\&.
.SS "\fBtest_cliparser::TestCLIParser::title\fP"
.PP
Definition at line 12 of file test_cliparser\&.py'\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Task-Organizer from the source code'\&.
