.TH "/home/scott/school/capstone/Task-Organizer/src/test/test_ctask.py" 3 "Wed Sep 28 2011" "Task-Organizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/scott/school/capstone/Task-Organizer/src/test/test_ctask.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBtest_ctask::TestCTask\fP"
.br
.RI "\fITests parsing of the command line for the ctask script'\&. \fP"
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "namespace \fBtest_ctask\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBtest_ctask::VERBOSITY\fP = util\&.verbosity_helper()"
.br
.ti -1c
.RI "tuple \fBtest_ctask::SUITE\fP = unittest\&.TestLoader()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Task-Organizer from the source code'\&.
