.TH "test_taskstorage::TestSQLiteStorage" 3 "Wed Sep 28 2011" "Task-Organizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_taskstorage::TestSQLiteStorage \- 
.PP
Tests specific to the SQLiteStorage class'\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBtest_taskstorage::TestStorage\fP'\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBsetUp\fP"
.br
.ti -1c
.RI "def \fBtearDown\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBmy_task\fP"
.br
.ti -1c
.RI "\fBtest_task_dbname\fP"
.br
.ti -1c
.RI "\fBtask_storage\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Tests specific to the SQLiteStorage class'\&. 

Tests that only apply to the implementation of the SQLiteStorage class and not other task_storage types'\&. 
.PP
Definition at line 262 of file test_taskstorage\&.py'\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def test_taskstorage::TestSQLiteStorage::__init__ (self, method_name)"
.PP
Reimplemented from \fBtest_taskstorage::TestStorage\fP'\&.
.PP
Definition at line 264 of file test_taskstorage\&.py'\&.
.SH "Member Function Documentation"
.PP 
.SS "def test_taskstorage::TestSQLiteStorage::setUp (self)"
.PP
Definition at line 267 of file test_taskstorage\&.py'\&.
.SS "def test_taskstorage::TestSQLiteStorage::tearDown (self)"
.PP
Definition at line 280 of file test_taskstorage\&.py'\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBtest_taskstorage::TestSQLiteStorage::my_task\fP"
.PP
Reimplemented from \fBtest_taskstorage::TestStorage\fP'\&.
.PP
Definition at line 267 of file test_taskstorage\&.py'\&.
.SS "\fBtest_taskstorage::TestSQLiteStorage::task_storage\fP"
.PP
Reimplemented from \fBtest_taskstorage::TestStorage\fP'\&.
.PP
Definition at line 267 of file test_taskstorage\&.py'\&.
.SS "\fBtest_taskstorage::TestSQLiteStorage::test_task_dbname\fP"
.PP
Definition at line 267 of file test_taskstorage\&.py'\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Task-Organizer from the source code'\&.
