.TH "test_taskstorage::TestGTaskStorage" 3 "Wed Sep 28 2011" "Task-Organizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_taskstorage::TestGTaskStorage \- 
.PP
Tests specific to the GTaskStorage class'\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBtest_taskstorage::TestStorage\fP'\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBsetUp\fP"
.br
.ti -1c
.RI "def \fBtearDown\fP"
.br
.ti -1c
.RI "def \fBtest_update_no_note\fP"
.br
.RI "\fITests that update() acts correctly when no note is specified'\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBmy_task\fP"
.br
.ti -1c
.RI "\fBtask_storage\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Tests specific to the GTaskStorage class'\&. 

Tests that only apply to the implementation of the GTaskStorage class and not other task_storage types'\&. 
.PP
Definition at line 297 of file test_taskstorage\&.py'\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def test_taskstorage::TestGTaskStorage::__init__ (self, method_name)"
.PP
Reimplemented from \fBtest_taskstorage::TestStorage\fP'\&.
.PP
Definition at line 299 of file test_taskstorage\&.py'\&.
.SH "Member Function Documentation"
.PP 
.SS "def test_taskstorage::TestGTaskStorage::setUp (self)"
.PP
Definition at line 302 of file test_taskstorage\&.py'\&.
.SS "def test_taskstorage::TestGTaskStorage::tearDown (self)"
.PP
Definition at line 311 of file test_taskstorage\&.py'\&.
.SS "def test_taskstorage::TestGTaskStorage::test_update_no_note (self)"
.PP
Tests that update() acts correctly when no note is specified'\&. 
.PP
Definition at line 319 of file test_taskstorage\&.py'\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBtest_taskstorage::TestGTaskStorage::my_task\fP"
.PP
Reimplemented from \fBtest_taskstorage::TestStorage\fP'\&.
.PP
Definition at line 302 of file test_taskstorage\&.py'\&.
.SS "\fBtest_taskstorage::TestGTaskStorage::task_storage\fP"
.PP
Reimplemented from \fBtest_taskstorage::TestStorage\fP'\&.
.PP
Definition at line 302 of file test_taskstorage\&.py'\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Task-Organizer from the source code'\&.
