.TH "test_taskcontroller::TestTaskControllerGTaskStorage" 3 "Wed Sep 28 2011" "Task-Organizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_taskcontroller::TestTaskControllerGTaskStorage \- 
.PP
Tests the TaskController while using GTask storage'\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBtest_taskcontroller::TestTaskController\fP'\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBsetUp\fP"
.br
.ti -1c
.RI "def \fBtearDown\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBinterface_controller\fP"
.br
.ti -1c
.RI "\fBtitle\fP"
.br
.ti -1c
.RI "\fBnotes\fP"
.br
.ti -1c
.RI "\fBkey\fP"
.br
.ti -1c
.RI "\fBadded_task\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Tests the TaskController while using GTask storage'\&. 
.PP
Definition at line 193 of file test_taskcontroller\&.py'\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def test_taskcontroller::TestTaskControllerGTaskStorage::__init__ (self, method_name)"
.PP
Reimplemented from \fBtest_taskcontroller::TestTaskController\fP'\&.
.PP
Definition at line 195 of file test_taskcontroller\&.py'\&.
.SH "Member Function Documentation"
.PP 
.SS "def test_taskcontroller::TestTaskControllerGTaskStorage::setUp (self)"
.PP
Definition at line 198 of file test_taskcontroller\&.py'\&.
.SS "def test_taskcontroller::TestTaskControllerGTaskStorage::tearDown (self)"
.PP
Definition at line 211 of file test_taskcontroller\&.py'\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBtest_taskcontroller::TestTaskControllerGTaskStorage::added_task\fP"
.PP
Reimplemented from \fBtest_taskcontroller::TestTaskController\fP'\&.
.PP
Definition at line 198 of file test_taskcontroller\&.py'\&.
.SS "\fBtest_taskcontroller::TestTaskControllerGTaskStorage::interface_controller\fP"
.PP
Reimplemented from \fBtest_taskcontroller::TestTaskController\fP'\&.
.PP
Definition at line 198 of file test_taskcontroller\&.py'\&.
.SS "\fBtest_taskcontroller::TestTaskControllerGTaskStorage::key\fP"
.PP
Definition at line 198 of file test_taskcontroller\&.py'\&.
.SS "\fBtest_taskcontroller::TestTaskControllerGTaskStorage::notes\fP"
.PP
Reimplemented from \fBtest_taskcontroller::TestTaskController\fP'\&.
.PP
Definition at line 198 of file test_taskcontroller\&.py'\&.
.SS "\fBtest_taskcontroller::TestTaskControllerGTaskStorage::title\fP"
.PP
Reimplemented from \fBtest_taskcontroller::TestTaskController\fP'\&.
.PP
Definition at line 198 of file test_taskcontroller\&.py'\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Task-Organizer from the source code'\&.
