.TH "test_task::TestTaskCreator" 3 "Wed Sep 28 2011" "Task-Organizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_task::TestTaskCreator \- 
.PP
Tests that TaskCreator correctly creates Task objects'\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBsetUp\fP"
.br
.ti -1c
.RI "def \fBtearDown\fP"
.br
.ti -1c
.RI "def \fBtest_build\fP"
.br
.RI "\fITests the creation of Task objects from dictionaries'\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBtitle\fP"
.br
.ti -1c
.RI "\fBnotes\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Tests that TaskCreator correctly creates Task objects'\&. 
.PP
Definition at line 67 of file test_task\&.py'\&.
.SH "Member Function Documentation"
.PP 
.SS "def test_task::TestTaskCreator::setUp (self)"
.PP
Definition at line 69 of file test_task\&.py'\&.
.SS "def test_task::TestTaskCreator::tearDown (self)"
.PP
Definition at line 73 of file test_task\&.py'\&.
.SS "def test_task::TestTaskCreator::test_build (self)"
.PP
Tests the creation of Task objects from dictionaries'\&. 
.PP
Definition at line 80 of file test_task\&.py'\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBtest_task::TestTaskCreator::notes\fP"
.PP
Definition at line 69 of file test_task\&.py'\&.
.SS "\fBtest_task::TestTaskCreator::title\fP"
.PP
Definition at line 69 of file test_task\&.py'\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Task-Organizer from the source code'\&.
