.TH "test_task" 3 "Wed Sep 28 2011" "Task-Organizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_task \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTestTask\fP"
.br
.RI "\fITests Task objects'\&. \fP"
.ti -1c
.RI "class \fBTestTaskCreator\fP"
.br
.RI "\fITests that TaskCreator correctly creates Task objects'\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBVERBOSITY\fP = util\&.verbosity_helper()"
.br
.ti -1c
.RI "tuple \fBSUITE\fP = unittest\&.TestLoader()"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "tuple \fBtest_task::SUITE\fP = unittest\&.TestLoader()"
.PP
Definition at line 96 of file test_task\&.py'\&.
.SS "tuple \fBtest_task::VERBOSITY\fP = util\&.verbosity_helper()"
.PP
Definition at line 94 of file test_task\&.py'\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Task-Organizer from the source code'\&.
