.TH "util" 3 "Wed Sep 28 2011" "Task-Organizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
util \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBverbosity_helper\fP"
.br
.ti -1c
.RI "def \fBprint_helper\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def util::print_helper ()"
.PP
Definition at line 18 of file util\&.py'\&.
.SS "def util::verbosity_helper ()"
.PP
Definition at line 7 of file util\&.py'\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Task-Organizer from the source code'\&.
