.TH "/home/scott/school/capstone/Task-Organizer/src/test/util.py" 3 "Wed Sep 28 2011" "Task-Organizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/scott/school/capstone/Task-Organizer/src/test/util.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Packages"

.in +1c
.ti -1c
.RI "namespace \fButil\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fButil::verbosity_helper\fP"
.br
.ti -1c
.RI "def \fButil::print_helper\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Task-Organizer from the source code'\&.
